// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRoScUFU4i7hLFT6oatWTkxuQLdk6N_wQ',
    appId: '1:419556458182:web:d4ce2e6f088e2b02dce1c7',
    messagingSenderId: '419556458182',
    projectId: 'trialxcodesxcs',
    authDomain: 'trialxcodesxcs.firebaseapp.com',
    storageBucket: 'trialxcodesxcs.appspot.com',
    measurementId: 'G-8H2VFM9TC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPRIgA11c2JWLhPj_pQrFA_-widyMEwDk',
    appId: '1:419556458182:android:6f1b63626465e85edce1c7',
    messagingSenderId: '419556458182',
    projectId: 'trialxcodesxcs',
    storageBucket: 'trialxcodesxcs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABqK7z46FAfJByq2qeDgjbqt98It9zh9Q',
    appId: '1:419556458182:ios:0ab6cd667a7eeda4dce1c7',
    messagingSenderId: '419556458182',
    projectId: 'trialxcodesxcs',
    storageBucket: 'trialxcodesxcs.appspot.com',
    iosClientId: '419556458182-n6g12lhhiuu4g6jqjhh7jrltgqtpbu7f.apps.googleusercontent.com',
    iosBundleId: 'com.xcodesxcs.xcodeTrialApp',
  );
}
