// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFMS_j_oL4O28SBS2Lt__ebs3HrYCcxBo',
    appId: '1:642340474649:web:56e042a722e25e04917f88',
    messagingSenderId: '642340474649',
    projectId: 'practicing-d9ec4',
    authDomain: 'practicing-d9ec4.firebaseapp.com',
    storageBucket: 'practicing-d9ec4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCn1qtysInQshItjqf6Hc9SrWQmt2GWLFY',
    appId: '1:642340474649:android:a2be345c82f6dac1917f88',
    messagingSenderId: '642340474649',
    projectId: 'practicing-d9ec4',
    storageBucket: 'practicing-d9ec4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1JQvnOJ1l76xZBm1mCLzEHOSHgapt9uc',
    appId: '1:642340474649:ios:9f0659108360e590917f88',
    messagingSenderId: '642340474649',
    projectId: 'practicing-d9ec4',
    storageBucket: 'practicing-d9ec4.appspot.com',
    iosClientId: '642340474649-41u0atsd6lid4gvas25m6snucijbl4nb.apps.googleusercontent.com',
    iosBundleId: 'com.example.untitled',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1JQvnOJ1l76xZBm1mCLzEHOSHgapt9uc',
    appId: '1:642340474649:ios:6a03ab74222e3163917f88',
    messagingSenderId: '642340474649',
    projectId: 'practicing-d9ec4',
    storageBucket: 'practicing-d9ec4.appspot.com',
    iosClientId: '642340474649-i2sal2qdfb0rnk8h9edno691u6s22vqv.apps.googleusercontent.com',
    iosBundleId: 'com.trijal.untitled',
  );
}
